//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chicken4WP.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Chicken4WP.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Messages 的本地化字符串。
        /// </summary>
        public static string HomePage_DM_Header {
            get {
                return ResourceManager.GetString("HomePage_DM_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Home 的本地化字符串。
        /// </summary>
        public static string HomePage_Index_Header {
            get {
                return ResourceManager.GetString("HomePage_Index_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mentions 的本地化字符串。
        /// </summary>
        public static string HomePage_Mention_Header {
            get {
                return ResourceManager.GetString("HomePage_Mention_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Detail 的本地化字符串。
        /// </summary>
        public static string StatusPage_Detail_Header {
            get {
                return ResourceManager.GetString("StatusPage_Detail_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Retweets 的本地化字符串。
        /// </summary>
        public static string StatusPage_Retweets_Header {
            get {
                return ResourceManager.GetString("StatusPage_Retweets_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FAVORITES 的本地化字符串。
        /// </summary>
        public static string StatusPage_StatusDetail_Favorites {
            get {
                return ResourceManager.GetString("StatusPage_StatusDetail_Favorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LOCATION 的本地化字符串。
        /// </summary>
        public static string StatusPage_StatusDetail_Location {
            get {
                return ResourceManager.GetString("StatusPage_StatusDetail_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RETWEETS 的本地化字符串。
        /// </summary>
        public static string StatusPage_StatusDetail_Retweets {
            get {
                return ResourceManager.GetString("StatusPage_StatusDetail_Retweets", resourceCulture);
            }
        }
    }
}
