//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chicken4WP.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Chicken4WP.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Messages 的本地化字符串。
        /// </summary>
        public static string HomePage_DM_Header {
            get {
                return ResourceManager.GetString("HomePage_DM_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Home 的本地化字符串。
        /// </summary>
        public static string HomePage_Index_Header {
            get {
                return ResourceManager.GetString("HomePage_Index_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mentions 的本地化字符串。
        /// </summary>
        public static string HomePage_Mention_Header {
            get {
                return ResourceManager.GetString("HomePage_Mention_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Detail 的本地化字符串。
        /// </summary>
        public static string StatusPage_Detail_Header {
            get {
                return ResourceManager.GetString("StatusPage_Detail_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Retweets 的本地化字符串。
        /// </summary>
        public static string StatusPage_Retweets_Header {
            get {
                return ResourceManager.GetString("StatusPage_Retweets_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FAVORITES 的本地化字符串。
        /// </summary>
        public static string StatusPage_StatusDetail_Favorites {
            get {
                return ResourceManager.GetString("StatusPage_StatusDetail_Favorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LOCATION 的本地化字符串。
        /// </summary>
        public static string StatusPage_StatusDetail_Location {
            get {
                return ResourceManager.GetString("StatusPage_StatusDetail_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RETWEETS 的本地化字符串。
        /// </summary>
        public static string StatusPage_StatusDetail_Retweets {
            get {
                return ResourceManager.GetString("StatusPage_StatusDetail_Retweets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 add to favorites successfully 的本地化字符串。
        /// </summary>
        public static string Toast_Msg_AddFavoriteSuccessfully {
            get {
                return ResourceManager.GetString("Toast_Msg_AddFavoriteSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 can not retweet private user&apos;s tweet 的本地化字符串。
        /// </summary>
        public static string Toast_Msg_CannotRetweetPrivateTweet {
            get {
                return ResourceManager.GetString("Toast_Msg_CannotRetweetPrivateTweet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 clear successfully 的本地化字符串。
        /// </summary>
        public static string Toast_Msg_ClearCacheSuccessfully {
            get {
                return ResourceManager.GetString("Toast_Msg_ClearCacheSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 delete successfully 的本地化字符串。
        /// </summary>
        public static string Toast_Msg_DeleteSuccessfully {
            get {
                return ResourceManager.GetString("Toast_Msg_DeleteSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 follow successfully 的本地化字符串。
        /// </summary>
        public static string Toast_Msg_FollowSuccessfully {
            get {
                return ResourceManager.GetString("Toast_Msg_FollowSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 hi, {0}~ 的本地化字符串。
        /// </summary>
        public static string Toast_Msg_HelloUser {
            get {
                return ResourceManager.GetString("Toast_Msg_HelloUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 message sent successfully 的本地化字符串。
        /// </summary>
        public static string Toast_Msg_MessageSentSuccessfully {
            get {
                return ResourceManager.GetString("Toast_Msg_MessageSentSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 no more mentions 的本地化字符串。
        /// </summary>
        public static string Toast_Msg_NoMoreMentions {
            get {
                return ResourceManager.GetString("Toast_Msg_NoMoreMentions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 no more retweets 的本地化字符串。
        /// </summary>
        public static string Toast_Msg_NoMoreRetweets {
            get {
                return ResourceManager.GetString("Toast_Msg_NoMoreRetweets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 no more tweet results for {0} 的本地化字符串。
        /// </summary>
        public static string Toast_Msg_NoMoreSearchTweetResults {
            get {
                return ResourceManager.GetString("Toast_Msg_NoMoreSearchTweetResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 no more user results for {0} 的本地化字符串。
        /// </summary>
        public static string Toast_Msg_NoMoreSearchUserResults {
            get {
                return ResourceManager.GetString("Toast_Msg_NoMoreSearchUserResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 no more tweets 的本地化字符串。
        /// </summary>
        public static string Toast_Msg_NoMoreTweets {
            get {
                return ResourceManager.GetString("Toast_Msg_NoMoreTweets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 no new mentions yet 的本地化字符串。
        /// </summary>
        public static string Toast_Msg_NoNewMentions {
            get {
                return ResourceManager.GetString("Toast_Msg_NoNewMentions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 no new retweets yet 的本地化字符串。
        /// </summary>
        public static string Toast_Msg_NoNewRetweets {
            get {
                return ResourceManager.GetString("Toast_Msg_NoNewRetweets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 no new tweets yet 的本地化字符串。
        /// </summary>
        public static string Toast_Msg_NoNewTweets {
            get {
                return ResourceManager.GetString("Toast_Msg_NoNewTweets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 no tweet results for {0} 的本地化字符串。
        /// </summary>
        public static string Toast_Msg_NoSearchTweetResults {
            get {
                return ResourceManager.GetString("Toast_Msg_NoSearchTweetResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 no user results for {0} 的本地化字符串。
        /// </summary>
        public static string Toast_Msg_NoSearchUserResults {
            get {
                return ResourceManager.GetString("Toast_Msg_NoSearchUserResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 only confirmed followers have access to user {0}&apos;s tweets 的本地化字符串。
        /// </summary>
        public static string Toast_Msg_NotFollowPrivateUser {
            get {
                return ResourceManager.GetString("Toast_Msg_NotFollowPrivateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 can&apos;t send message to {0} who not follow you 的本地化字符串。
        /// </summary>
        public static string Toast_Msg_NotFollowYou {
            get {
                return ResourceManager.GetString("Toast_Msg_NotFollowYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove favorites successfully 的本地化字符串。
        /// </summary>
        public static string Toast_Msg_RemoveFavoriteSuccessfully {
            get {
                return ResourceManager.GetString("Toast_Msg_RemoveFavoriteSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 request sent successfully 的本地化字符串。
        /// </summary>
        public static string Toast_Msg_RequestSentSuccessfully {
            get {
                return ResourceManager.GetString("Toast_Msg_RequestSentSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 retweet successfully 的本地化字符串。
        /// </summary>
        public static string Toast_Msg_RetweetSuccessfully {
            get {
                return ResourceManager.GetString("Toast_Msg_RetweetSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 tweet sent successfully 的本地化字符串。
        /// </summary>
        public static string Toast_Msg_TweetSentSuccessfully {
            get {
                return ResourceManager.GetString("Toast_Msg_TweetSentSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 unfollow successfully 的本地化字符串。
        /// </summary>
        public static string Toast_Msg_UnfollowSuccessfully {
            get {
                return ResourceManager.GetString("Toast_Msg_UnfollowSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 aw, some unknown error happened 的本地化字符串。
        /// </summary>
        public static string Toast_Msg_UnknowError {
            get {
                return ResourceManager.GetString("Toast_Msg_UnknowError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 update successfully 的本地化字符串。
        /// </summary>
        public static string Toast_Msg_UpdateMyProfileSuccessfully {
            get {
                return ResourceManager.GetString("Toast_Msg_UpdateMyProfileSuccessfully", resourceCulture);
            }
        }
    }
}
